//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Continental.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public decimal Contract_ID { get; set; }
        public string Contract_Name { get; set; }
        public decimal Hitman_ID { get; set; }
        public decimal Target_ID { get; set; }
        public Nullable<decimal> Extra_Wish_ID { get; set; }
    
        public virtual Hitman Hitman { get; set; }
        public virtual Target Target { get; set; }
        public virtual ExtraWish ExtraWish { get; set; }
    }
}
